const components = [
  {
    id: '1',
    img: '/img/2.jpg',
    width: '523',
    height: '653',
    alt: 'Gallery Image',
    text: 'fashion',
    title: 'The Battle',
    tag: 'motion',
  },
  {
    id: '2',
    img: '/img/2.jpg',
    width: '523',
    height: '523',
    alt: 'Gallery Image',
    text: 'digital art',
    title: 'Processors',
    tag: 'photo',
  },
  {
    id: '3',
    img: '/img/2.jpg',
    width: '523',
    height: '642',
    alt: 'Gallery Image',
    text: 'art direction',
    title: 'Tempo',
    tag: 'branding',
  },
  {
    id: '4',
    img: '/img/1.jpg',
    width: '523',
    height: '361',
    alt: 'Gallery Image',
    text: 'fashion',
    title: 'LEtoile Feb',
    tag: 'motion',
  },
  {
    id: '5',
    img: '/img/1.jpg',
    width: '523',
    height: '348',
    alt: 'Gallery Image',
    text: 'advertising',
    title: 'Kresios',
    tag: 'photo',
  },
  {
    id: '6',
    img: '/img/2.jpg',
    width: '523',
    height: '579',
    alt: 'Gallery Image',
    text: 'architecture',
    title: 'Hospitality',
    tag: 'branding',
  },
  {
    id: '7',
    img: '/img/2.jpg',
    width: '523',
    height: '677',
    alt: 'Gallery Image',
    text: 'architecture',
    title: 'Mrsoet',
    tag: 'motion',
  },
  {
    id: '8',
    img: '/img/1.jpg',
    width: '523',
    height: '294',
    alt: 'Gallery Image',
    text: 'photography',
    title: 'Dark Dream',
    tag: 'photo',
  },
];

export default components;
