const components = [
  {
    id: '1',
    link: '#',
    img: '/img/1.jpg',
    width: '642',
    height: '475',
    alt: 'Gallery Image',
    text: 'photography',
    title: 'Dark Dream',
  },
  {
    id: '2',
    link: '#',
    img: '/img/1.jpg',
    width: '642',
    height: '475',
    alt: 'Gallery Image',
    text: 'fashion',
    title: 'LEtoile Feb',
  },
  {
    id: '3',
    link: '#',
    img: '/img/1.jpg',
    width: '642',
    height: '475',
    alt: 'Gallery Image',
    text: 'art direction',
    title: 'Tempo',
  },
  {
    id: '4',
    link: '#',
    img: '/img/1.jpg',
    width: '642',
    height: '475',
    alt: 'Gallery Image',
    text: 'advertising',
    title: 'Kresios',
  },
  {
    id: '5',
    link: '#',
    img: '/img/1.jpg',
    width: '642',
    height: '475',
    alt: 'Gallery Image',
    text: 'fashion',
    title: 'The Battle',
  },
  {
    id: '6',
    link: '#',
    img: '/img/1.jpg',
    width: '642',
    height: '475',
    alt: 'Gallery Image',
    text: 'architecture',
    title: 'Hospitality',
  },
  {
    id: '7',
    link: '#',
    img: '/img/1.jpg',
    width: '642',
    height: '475',
    alt: 'Gallery Image',
    text: 'digital art',
    title: 'Processors',
  },
  {
    id: '8',
    link: '#',
    img: '/img/1.jpg',
    width: '642',
    height: '475',
    alt: 'Gallery Image',
    text: 'architecture',
    title: 'Mrsoet',
  },
];

export default components;
